typography_spectrum: 0.13309897924773395
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.7668206407688558
  lightness: 0.7144065997563303
  saturation: 0.8654086829628795
  rhythmicContrast: 0.39859920274466276
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7464382643811405
analytics:
  google: null
  facebook: null
  twitter: null
name: GridLife
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Novel | Scamalot Episode #5'
    id: 91781a27-4c05-4311-a936-c32bfe05be87
    type: content
favicon: null
title: Grid Life
purpose: []
