name: GridLife
favicon: null
layout_spectrum: 0.8871722638141364
typography_spectrum: 0.6667264346033335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.16112040542066097
  lightness: 0.13292621821165085
  saturation: 0.5795231976080686
  rhythmicContrast: 0.6658776407130063
purpose: []
